<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AnimalShelter.MigrationService-d5247b4e-cab0-470f-aea0-5afd945a7c31</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnimalShelter.Api\AnimalShelter.Api.csproj" />
    <ProjectReference Include="..\AnimalShelter.ServiceDefaults\AnimalShelter.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
