### Создать животное
# @name createAnimal
POST {{host}}/animals
Content-Type: application/json

{
  "name": "Рекс",
  "species": "Собака",
  "dateOfBirth": "2022-05-01"
}

### Создать животное с датой прибытия
POST {{host}}/animals
Content-Type: application/json

{
  "name": "Жора",
  "species": "Собака",
  "dateOfBirth": "2022-05-01",
  "intakeDate": "2026-07-10T00:00:00Z"
}

### Получить животное по id
GET {{host}}/animals/{{createAnimal.response.body.$.id}}

### Список животных с пагинацией
GET {{host}}/animals?Page=1&PageSize=10